/**
 * Comprehensive collection of real-world place names for dictation practice.
 * These are names that commonly occur in real conversations - over the phone,
 * when giving directions, discussing travel, or filling out forms.
 */

// Countries - common in travel and address contexts
const COUNTRIES = [
  'Afghanistan',
  'Argentina',
  'Australia',
  'Austria',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Cambodia',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Denmark',
  'Ecuador',
  'Egypt',
  'Ethiopia',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kenya',
  'Kuwait',
  'Lebanon',
  'Malaysia',
  'Mexico',
  'Morocco',
  'Nepal',
  'Netherlands',
  'Nigeria',
  'Norway',
  'Pakistan',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Scotland',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Tunisia',
  'Turkey',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'Venezuela',
  'Vietnam',
  'Wales',
  'Zimbabwe',
]

// Major world cities - commonly mentioned in conversations
const WORLD_CITIES = [
  'Amsterdam',
  'Ankara',
  'Athens',
  'Auckland',
  'Baghdad',
  'Bangkok',
  'Barcelona',
  'Beijing',
  'Belgrade',
  'Berlin',
  'Bogota',
  'Bologna',
  'Bordeaux',
  'Brisbane',
  'Brussels',
  'Budapest',
  'Buenos Aires',
  'Cairo',
  'Calcutta',
  'Calgary',
  'Cape Town',
  'Casablanca',
  'Copenhagen',
  'Damascus',
  'Delhi',
  'Dresden',
  'Dubai',
  'Dublin',
  'Edinburgh',
  'Florence',
  'Frankfurt',
  'Geneva',
  'Glasgow',
  'Hamburg',
  'Hanoi',
  'Helsinki',
  'Hong Kong',
  'Istanbul',
  'Jakarta',
  'Jerusalem',
  'Johannesburg',
  'Kampala',
  'Karachi',
  'Kyoto',
  'Lagos',
  'Lima',
  'Lisbon',
  'Liverpool',
  'London',
  'Madrid',
  'Manchester',
  'Manila',
  'Marrakech',
  'Marseille',
  'Melbourne',
  'Milan',
  'Montreal',
  'Moscow',
  'Mumbai',
  'Munich',
  'Nairobi',
  'Naples',
  'Osaka',
  'Oslo',
  'Ottawa',
  'Paris',
  'Perth',
  'Prague',
  'Quebec',
  'Reykjavik',
  'Rio',
  'Riyadh',
  'Rome',
  'Rotterdam',
  'Santiago',
  'Sao Paulo',
  'Seoul',
  'Seville',
  'Shanghai',
  'Singapore',
  'Stockholm',
  'Sydney',
  'Taipei',
  'Tehran',
  'Tokyo',
  'Toronto',
  'Valencia',
  'Vancouver',
  'Venice',
  'Vienna',
  'Warsaw',
  'Wellington',
  'Zurich',
]

// US states - commonly used in addresses
const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]

// US cities - commonly referenced
const US_CITIES = [
  'Albuquerque',
  'Anchorage',
  'Atlanta',
  'Austin',
  'Baltimore',
  'Boise',
  'Boston',
  'Buffalo',
  'Charlotte',
  'Chicago',
  'Cincinnati',
  'Cleveland',
  'Columbus',
  'Dallas',
  'Denver',
  'Detroit',
  'El Paso',
  'Fort Worth',
  'Fresno',
  'Hartford',
  'Honolulu',
  'Houston',
  'Indianapolis',
  'Jacksonville',
  'Kansas City',
  'Las Vegas',
  'Long Beach',
  'Los Angeles',
  'Louisville',
  'Memphis',
  'Miami',
  'Milwaukee',
  'Minneapolis',
  'Nashville',
  'New Orleans',
  'Oakland',
  'Oklahoma City',
  'Omaha',
  'Orlando',
  'Philadelphia',
  'Phoenix',
  'Pittsburgh',
  'Portland',
  'Providence',
  'Raleigh',
  'Richmond',
  'Sacramento',
  'Salt Lake City',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'Santa Fe',
  'Seattle',
  'St. Louis',
  'Tampa',
  'Tucson',
  'Tulsa',
  'Virginia Beach',
  'Washington',
]

// UK cities and towns
const UK_CITIES = [
  'Aberdeen',
  'Bath',
  'Belfast',
  'Birmingham',
  'Blackpool',
  'Bolton',
  'Bournemouth',
  'Bradford',
  'Brighton',
  'Bristol',
  'Cambridge',
  'Canterbury',
  'Cardiff',
  'Carlisle',
  'Chester',
  'Coventry',
  'Derby',
  'Dundee',
  'Durham',
  'Exeter',
  'Gloucester',
  'Greenwich',
  'Inverness',
  'Ipswich',
  'Lancaster',
  'Leeds',
  'Leicester',
  'Lincoln',
  'Luton',
  'Maidstone',
  'Newcastle',
  'Norwich',
  'Nottingham',
  'Oxford',
  'Plymouth',
  'Portsmouth',
  'Preston',
  'Reading',
  'Sheffield',
  'Southampton',
  'Stratford',
  'Sunderland',
  'Swansea',
  'Swindon',
  'Watford',
  'Westminster',
  'Winchester',
  'Windsor',
  'Worcester',
  'York',
]

// Common street names that appear in addresses
const STREET_NAMES = [
  'Baker Street',
  'Beacon Street',
  'Broadway',
  'Cedar Lane',
  'Central Avenue',
  'Cherry Lane',
  'Chestnut Street',
  'Church Street',
  'College Avenue',
  'Columbia Road',
  'Cypress Drive',
  'Division Street',
  'Elm Street',
  'Fifth Avenue',
  'First Street',
  'Forest Drive',
  'Franklin Street',
  'Garden Road',
  'Grand Avenue',
  'Grove Street',
  'Harbor Drive',
  'High Street',
  'Highland Avenue',
  'Hill Street',
  'Jackson Street',
  'Jefferson Avenue',
  'King Street',
  'Lake Drive',
  'Lincoln Avenue',
  'Lombard Street',
  'Madison Avenue',
  'Main Street',
  'Maple Avenue',
  'Market Street',
  'Meadow Lane',
  'Mill Road',
  'Oak Street',
  'Ocean Boulevard',
  'Park Avenue',
  'Park Lane',
  'Pearl Street',
  'Pine Street',
  'Pleasant Street',
  'Prospect Avenue',
  'Railroad Avenue',
  'Ridge Road',
  'River Road',
  'Riverside Drive',
  'School Street',
  'Second Avenue',
  'Spring Street',
  'State Street',
  'Sunset Boulevard',
  'Third Street',
  'Union Street',
  'Valley Road',
  'Victoria Street',
  'View Drive',
  'Walnut Street',
  'Washington Street',
  'Water Street',
  'Willow Lane',
  'Windsor Road',
]

// Famous landmarks and locations
const LANDMARKS = [
  'Alcatraz',
  'Alhambra',
  'Angkor Wat',
  'Big Ben',
  'Brooklyn Bridge',
  'Buckingham Palace',
  'Central Park',
  'Colosseum',
  'Eiffel Tower',
  'Empire State Building',
  'Golden Gate Bridge',
  'Grand Canyon',
  'Great Wall',
  'Kremlin',
  'Liberty Island',
  'Lincoln Memorial',
  'Louvre',
  'Machu Picchu',
  'Mount Everest',
  'Mount Fuji',
  'Mount Rushmore',
  'Niagara Falls',
  'Notre Dame',
  'Parthenon',
  'Petra',
  'Piccadilly Circus',
  'Red Square',
  'Sahara',
  'Sistine Chapel',
  'Statue of Liberty',
  'Stonehenge',
  'Sydney Opera House',
  'Taj Mahal',
  'Times Square',
  'Tower Bridge',
  'Tower of London',
  'Trafalgar Square',
  'Vatican',
  'Versailles',
  'Westminster Abbey',
  'Yellowstone',
]

// Canadian cities
const CANADIAN_CITIES = [
  'Banff',
  'Brampton',
  'Burlington',
  'Burnaby',
  'Edmonton',
  'Gatineau',
  'Halifax',
  'Hamilton',
  'Kelowna',
  'Kingston',
  'Kitchener',
  'Laval',
  'London',
  'Markham',
  'Mississauga',
  'Moncton',
  'Niagara',
  'Oakville',
  'Regina',
  'Richmond',
  'Saskatoon',
  'Surrey',
  'Victoria',
  'Whitehorse',
  'Winnipeg',
]

// Australian cities
const AUSTRALIAN_CITIES = [
  'Adelaide',
  'Ballarat',
  'Bendigo',
  'Cairns',
  'Canberra',
  'Darwin',
  'Geelong',
  'Gold Coast',
  'Hobart',
  'Launceston',
  'Newcastle',
  'Sunshine Coast',
  'Toowoomba',
  'Townsville',
  'Wollongong',
]

// European regions and areas commonly mentioned
const EUROPEAN_REGIONS = [
  'Alsace',
  'Andalusia',
  'Bavaria',
  'Brittany',
  'Burgundy',
  'Catalonia',
  'Champagne',
  'Cornwall',
  'Corsica',
  'Flanders',
  'Galicia',
  'Lombardy',
  'Normandy',
  'Provence',
  'Sardinia',
  'Saxony',
  'Sicily',
  'Thessaly',
  'Transylvania',
  'Tuscany',
  'Tyrol',
  'Wallonia',
]

// All place names combined for random selection
export const ALL_PLACE_NAMES = [
  ...COUNTRIES,
  ...WORLD_CITIES,
  ...US_STATES,
  ...US_CITIES,
  ...UK_CITIES,
  ...STREET_NAMES,
  ...LANDMARKS,
  ...CANADIAN_CITIES,
  ...AUSTRALIAN_CITIES,
  ...EUROPEAN_REGIONS,
]

// Category-based exports for potential future use
export const PLACE_CATEGORIES = {
  countries: COUNTRIES,
  worldCities: WORLD_CITIES,
  usStates: US_STATES,
  usCities: US_CITIES,
  ukCities: UK_CITIES,
  streetNames: STREET_NAMES,
  landmarks: LANDMARKS,
  canadianCities: CANADIAN_CITIES,
  australianCities: AUSTRALIAN_CITIES,
  europeanRegions: EUROPEAN_REGIONS,
} as const

export type PlaceCategory = keyof typeof PLACE_CATEGORIES

/**
 * Get a random place name from all categories
 */
export function getRandomPlaceName(): string {
  return ALL_PLACE_NAMES[Math.floor(Math.random() * ALL_PLACE_NAMES.length)]
}

/**
 * Get a random place name from a specific category
 */
export function getRandomPlaceNameFromCategory(category: PlaceCategory): string {
  const names = PLACE_CATEGORIES[category]
  return names[Math.floor(Math.random() * names.length)]
}

/**
 * Get total count of available place names
 */
export function getPlaceNameCount(): number {
  return ALL_PLACE_NAMES.length
}
